git functions run in subshell and set -euo

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,10 +2,11 @@
 
 ## git
 gdifff () { git diff --color "$@" | diff-so-fancy; }
-prune () {
-  local branch_name="$(git rev-parse --abbrev-ref HEAD)"
+prune () (
+  set -euo pipefail
 
-  local git_action
+  branch_name="$(git rev-parse --abbrev-ref HEAD)"
+
   if [[ "${branch_name}" =~ ^(master|develop)$ ]]; then
     git_action=pull
   else
@@ -13,28 +14,29 @@ prune () {
   fi
   echo $(tput setaf 6)git $git_action origin --prune$(tput sgr0)
   git $git_action origin --prune
-}
-push () {
-  local branch_name="$(git rev-parse --abbrev-ref HEAD)"
-  local cmd
-  local THE_answer
-  if [[ "${branch_name}" =~ ^(master|develop)$ ]]; then
-    echo "Cannot push to master or develop"
+)
+push () (
+  set -euo pipefail
+
+  branch_name="$(git rev-parse --abbrev-ref HEAD)"
+
+  [[ "${branch_name}" =~ ^(master|develop)$ ]] &&
+    echo "Cannot push to master or develop" &&
     return 1
+
+  if [ "${1:-}" == "force" ]; then
+    cmd="git push origin --force-with-lease"
+    color_cmd="git push origin $(tput setaf 1)--force-with-lease $(tput setaf 2)$branch_name$(tput sgr0)"
   else
-    if [ "$1" == "force" ]; then
-      cmd="git push origin --force-with-lease"
-    else
-      cmd="git push origin"
-    fi
-    echo $cmd $(tput setaf 2)$branch_name$(tput sgr0) | sed 's/\(--force-with-lease\)/'$(tput setaf 1)'&'$(tput sgr0)'/'
-    printf "[type 42 to continue] "
-    read THE_answer
-    if [ "${THE_answer}" = "42" ]; then
-      $cmd $branch_name
-    fi
+    cmd="git push origin"
+    color_cmd="git push origin $(tput setaf 2)$branch_name$(tput sgr0)"
   fi
-}
+
+  echo "$color_cmd"
+  read -p "[type 42 to continue] " THE_answer
+  [[ "${THE_answer}" = "42" ]]
+  $cmd $branch_name
+)
 
 ## subl
 sf. () {
